[project]
name = "python-asyncio"
version = "0.1.0"
description = "AsyncIO - Asynchronous Programming"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.3.0",
    "requests>=2.32.5",
]
